### ISSUE TITLE
話数移動時にコメントが取得できない

### ISSUE THREAD

**Issue by shsw228** [sopisoft/d-comments#70]
## 概要

次話数に移った場合にコメントが取得できないことがある。取得できなかった場合以降も取得されない。

## 環境
- MacOS 14.4.1 (23E224), Chrome Version 124.0.6367.80 (Official Build) (arm64)
- d-anime comments viewer v2024.4.10

## 備考
- Chromeで新規プロファイルを作成しこの拡張機能のみが入っている状態でも再現する。
- 再生画面を更新するとコメントは取得できるので存在しないわけではない。
- [ダンジョン飯](https://animestore.docomo.ne.jp/animestore/ci_pc?workId=26747) の発生率が高い。

## 設定(Local Storage)
```json
{
  "allow_login_to_nicovideo": true,
  "auto_search": true,
  "enable_auto_play": true,
  "read_how_to_use": "1.0.0"
}

```

**Comment by sopisoft** [comment]
詳細な情報ありがとうございます
確認しますっ！

**Comment by sopisoft** [comment]
修正しました！
