### ISSUE TITLE
話数一覧画面で新しいタブでコメントを表示しながら再生ボタンが表示されない

### ISSUE THREAD

**Issue by shsw228** [sopisoft/d-comments#83]
https://github.com/sopisoft/d-comments/releases/tag/v2024.9.16
上のPRより表題の事象が発生します。

- 過去ビルドに戻して表示されること
- 設定で表示するにチェックが入っていること
を確認しました。

```
Uncaught (in promise) SecurityError: Failed to construct 'Worker': Script at 'chrome-extension://jlneocomonflkaljaodapefnoegbjokn/assets/comments_worker-Ck1GVp3g.js' cannot be accessed from origin 'https://animestore.docomo.ne.jp'.
Context
``` 
エラー内容はこのようになっています。

**Comment by sopisoft** [comment]
ご報告ありがとうございます。Chromium 系ブラウザで再現できました。

[v2024.9.16](https://github.com/sopisoft/d-comments/releases/tag/v2024.9.16) でパフォーマンス向上のため導入した Web Worker が、Chrome では file: プロトコルで実行できないことが原因でした。

すぐ修正します！

**Comment by sopisoft** [comment]
[v2024.9.18](https://github.com/sopisoft/d-comments/releases/tag/v2024.9.18) で修正されました。
